name: commit ci
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v6

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint
        # report style issues without blocking the build artifacts
        continue-on-error: true
        run: swiftlint

      - name: Configure build environment
        run: |
          echo git_ref_name="$(git describe --always)" >> $GITHUB_ENV

      - name: Build Squirrel
        run: ./action-build.sh package

      - name: Zip Squirrel.app
        run: ditto -c -k --keepParent build/Build/Products/Release/Squirrel.app package/Squirrel.app.zip

      - name: Upload Squirrel installer
        uses: actions/upload-artifact@v6
        with:
          name: Squirrel-${{ env.git_ref_name }}-pkg
          path: package/*.pkg
          # keep 90 days
          retention-days: 90

      - name: Upload Squirrel.app
        uses: actions/upload-artifact@v6
        with:
          name: Squirrel-${{ env.git_ref_name }}-app
          path: package/Squirrel.app.zip
          retention-days: 90

      - name: Install periphery
        continue-on-error: true
        run: brew install peripheryapp/periphery/periphery

      - name: Check Unused Code
        continue-on-error: true
        run: periphery scan --relative-results --skip-build --index-store-path build/Index.noindex/DataStore
